---
title: "DSerna_LiveSession9Assignment"
author: "Daniel Serna"
date: "July 10, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1

### Question 1b

```{r scrapeCast}
#load rvest library
if(!require(rvest)) install.packages("rvest")
library(rvest)

url <- 'http://www.imdb.com/title/tt1201607/fullcredits?ref_=tt_ql_1'
#read the page into a variable.
harryPotterPage <- read_html(url)

#XPath derived from browser tools.
castTableXPath <- '//*[@id="fullcredits_content"]/table[3]'

#read cast table into a variable
castTable <- html_nodes(harryPotterPage, xpath = castTableXPath)

#convert cast table into a dataframe
castDF <- as.data.frame(html_table(castTable))
```

### Question 1c
```{r cleanCastDF}
#remove unnecessary columns and blank first row
castDF <- castDF[-c(1),-c(1,3)]

#rename columns
colnames(castDF) <- c("Actor", "Character")

#rectify Warwick Davis character name
castDF[castDF$Actor == "Warwick Davis",]$Character = "Griphook / Professor Filius Flitwick"

#remove "Rest of cast listed alphabetically:" row
castDF <- castDF[!(castDF$Actor=="Rest of cast listed alphabetically:"),]
```

### Question 1d
```{r splitActorName}
#load stringi library
library(stringi)

#create formula to splice off first name (and middle if applicable)
firstName <- function(nameVector){
  returnVector <- c()
  for (i in 1:length(nameVector)){
    names <- stri_extract_all_words(nameVector[i], simplify=TRUE)
    returnValue <- paste(names[1,1:length(names)-1], sep = " ")
    returnValue <- paste(returnValue, collapse=" ")
    returnVector[i] <- returnValue
  }
  returnVector
}

#create formula to splice off surname
surname <- function(nameVector){
  returnVector <- c()
  for (i in 1:length(nameVector)){
    names <- stri_extract_all_words(nameVector[i], simplify=TRUE)
    returnValue <- names[length(names)]
    returnVector[i] <- returnValue
  }
  returnVector
}

#run firstName and surname formulas on castDF to split actor name data
castDF$FirstName <- firstName(castDF$Actor)
castDF$Surname <- surname(castDF$Actor)

#remove actor column
castDF <- castDF[, -c(1)]
```

### Question 1e
```{r headCastDF}
head(castDF, 10)
```

## Question 2

### Question 2b

```{r scrapeShootingStats}
url <- 'http://www.espn.com/nba/team/stats/_/name/sa/san-antonio-spurs'
#read the page into a variable.
espnPage <- read_html(url)

#XPath derived from browser tools.
shootingTableXPath <- '//*[@id="my-players-table"]/div[4]/div[3]/table'

#read shooting table into a variable
shootingTable <- html_nodes(espnPage, xpath = shootingTableXPath)

#convert shooting table into a dataframe
shootingDF <- as.data.frame(html_table(shootingTable))
```

### Question 2c
```{r cleanShootingDF}
#assign column names from existing row
colnames(shootingDF) <- shootingDF[2,]

#remove first 2 unnecessary rows
shootingDF <- shootingDF[-c(1:2),]

#remove totals row
shootingDF <- shootingDF[-c(nrow(shootingDF)),]

#create formula to splice off player name
playerName <- function(nameVector){
  returnVector <- c()
  for (i in 1:length(nameVector)){
    names <- stri_extract_all_words(nameVector[i], simplify=TRUE)
    returnValue <- paste(names[1,1:length(names)-1], sep = " ")
    returnValue <- paste(returnValue, collapse=" ")
    returnVector[i] <- returnValue
  }
  returnVector
}

#create formula to splice off position
position <- function(nameVector){
  returnVector <- c()
  for (i in 1:length(nameVector)){
    names <- stri_extract_all_words(nameVector[i], simplify=TRUE)
    returnValue <- names[length(names)]
    returnVector[i] <- returnValue
  }
  returnVector
}

#run playerName and position formulas on shootingDF to split player data
shootingDF$Name <- playerName(shootingDF$PLAYER)
shootingDF$Position <- position(shootingDF$PLAYER)

#remove player column
shootingDF <- shootingDF[, -c(1)]

#check data types of all columns
sapply(shootingDF, class)

#convert relevant columns to numeric
shootingDF[,1:14] <- sapply(shootingDF[,1:14], as.numeric)

#check data types of all columns
sapply(shootingDF, class)
```

### Question 2d
```{r barChart}
#create bar plot with flipped orientation, axis labels, centered title, and colored categories
library(ggplot2)
plot <- ggplot(data = shootingDF, aes(x = shootingDF$Name, y = shootingDF$`FG%`, fill = shootingDF$Position)) + geom_bar(stat="identity") + ggtitle("Field goals percentage per game by player") +
  theme(plot.title = element_text(hjust = 0.5)) + 
  ylab("Field goal percentage") + 
  xlab("Player name") + labs(fill = "Position")
plot + coord_flip()
```

## Github location
https://github.com/djserna/msds-6306-homework/tree/master/Unit9